### ISSUE TITLE
public auth fail on circleCI test runner

### ISSUE THREAD

**Issue by jjtolton** [cognitect-labs/test-runner#23]
This isn't really your problem, per se, but it did prevent me being able to use the cognitect-lab test runner in CI/CD.
Note: the `clojure -A:test:runner` works locally but not in circleCI on cloud.  In this case, a explanation would probably be an acceptable solution as I I don't believe this is a bug in the software.  

This is the circleCI error:

```Error building classpath. ssh://git@github.com/cognitect-labs/test-runner.git: Auth fail
org.eclipse.jgit.api.errors.TransportException: ssh://git@github.com/cognitect-labs/test-runner.git: Auth fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:248)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:306)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:200)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:89)
	at clojure.tools.gitlibs.impl$call_with_auth.invokeStatic(impl.clj:52)
	at clojure.tools.gitlibs.impl$call_with_auth.invoke(impl.clj:43)
	at clojure.tools.gitlibs.impl$git_clone_bare.invokeStatic(impl.clj:73)
	at clojure.tools.gitlibs.impl$git_clone_bare.invoke(impl.clj:70)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invokeStatic(impl.clj:112)
	at clojure.tools.gitlibs.impl$ensure_git_dir.invoke(impl.clj:102)
	at clojure.tools.gitlibs$resolve.invokeStatic(gitlibs.clj:33)
	at clojure.tools.gitlibs$resolve.invoke(gitlibs.clj:29)
	at clojure.tools.gitlibs$procure.invokeStatic(gitlibs.clj:47)
	at clojure.tools.gitlibs$procure.invoke(gitlibs.clj:41)
	at clojure.tools.deps.alpha.extensions.git$eval1259$fn__1261.invoke(git.clj:42)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:386)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:354)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:444)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:424)
	at clojure.tools.deps.alpha$calc_basis.invokeStatic(alpha.clj:550)
	at clojure.tools.deps.alpha$calc_basis.invoke(alpha.clj:525)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invokeStatic(make_classpath2.clj:86)
	at clojure.tools.deps.alpha.script.make_classpath2$run_core.invoke(make_classpath2.clj:56)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:109)
	at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:103)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:158)
	at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:128)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://git@github.com/cognitect-labs/test-runner.git: Auth fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:172)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:137)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:123)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1269)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:237)
	... 37 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:519)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:126)
	... 44 more
```

I couldn't find anything online about it.  

**deps.edn**
```clojure
{:mvn/repos {"clojars" {:url "https://repo.clojars.org/"}
             "central" {:url "https://repo1.maven.org/maven2/"}}
 :paths     ["src" "resources"]
 :deps      {org.clojure/clojure                  {:mvn/version "1.10.1"}
             techascent/tech.ml.dataset           {:mvn/version "5.00-beta-6"}
             org.apache.hadoop/hadoop-common      {:mvn/version "3.1.1"}
             org.apache.arrow/arrow-memory-unsafe {:mvn/version "2.0.0"}
             org.apache.arrow/arrow-memory-core   {:mvn/version "2.0.0"}
             org.apache.arrow/arrow-vector        {:mvn/version "2.0.0"}
             cnuernber/dtype-next                 {:mvn/version "6.00-beta-5"}}
 :aliases   {:test   {:extra-paths ["test"]}
             :runner { :extra-deps
                      {com.cognitect/test-runner
                       {:git/url "https://github.com/cognitect-labs/test-runner.git"
                        :sha     "209b64504cb3bd3b99ecfec7937b358a879f55c1"}}
                      :main-opts   ["-m" "cognitect.test-runner"]}}}
```

**.circleCI**
```yml
version: 2.1
jobs:
  build:
    working_directory: ********************
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.619
    environment:
      - CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          key: ********************
      - run:
          name: Run all tests
          command: clojure -A:test:runner
      - save_cache:
          paths:
            - ~/.m2
          key: ****************
      - store_artifacts:
          path: /tmp/artifacts
```

**Comment by FiV0** [comment]
@jjtolton This has nothing to do with the test-runner, but rather a problem of a bad default setup of CircleCI. Try this
```yml
    steps:
      - checkout
      - run:
          name: Get rid of erroneous git config
          command: |
              rm -rf ~/.gitconfig
```

**Comment by jjtolton** [comment]
Thank you!  I assumed it had nothing to do with the test-runner but I was
having trouble diagnosing.  You can close this.  Thank you!

**Comment by gmemstr** [comment]
Interesting - I assume this is because of how we setup during the `checkout` phase. I'll raise this internally and see if it's something we can easily work around. My best guess is that our SSH keys we deploy to clone over SSH are only valid for a repository, but try to be used everywhere.

**Comment by puredanger** [comment]
This is correctly diagnosed above but just want to mention that the newest version of clj shells out to git and this should actually work now (as you can ssh to get public repos just fine).

**Comment by jjtolton** [comment]
you da man!
